import Database from "better-sqlite3";
import { mkdirSync } from "node:fs";
import { dirname, join } from "node:path";

// Resolve data locations from the environment so the same code runs locally
// and inside Docker (where DATA_DIR=/data).
const DATA_DIR = process.env.DATA_DIR ?? join(process.cwd(), "..", "data");
export const MUSIC_DIR = join(DATA_DIR, "music");
export const ART_DIR = join(DATA_DIR, "art");
const DB_PATH = join(DATA_DIR, "app.db");

let db: Database.Database | null = null;

// Returns a singleton database connection, creating the schema and required
// directories on first use.
export function getDb(): Database.Database {
  if (db) return db;

  mkdirSync(MUSIC_DIR, { recursive: true });
  mkdirSync(ART_DIR, { recursive: true });
  mkdirSync(dirname(DB_PATH), { recursive: true });

  db = new Database(DB_PATH);
  db.pragma("journal_mode = WAL");
  db.pragma("foreign_keys = ON");
  migrate(db);
  return db;
}

export function migrate(database: Database.Database): void {
  database.exec(`
    CREATE TABLE IF NOT EXISTS songs (
      id                INTEGER PRIMARY KEY AUTOINCREMENT,
      filename          TEXT NOT NULL,
      original_filename TEXT NOT NULL,
      uploaded_at       TEXT NOT NULL DEFAULT (datetime('now'))
    );

    CREATE TABLE IF NOT EXISTS playlists (
      id         INTEGER PRIMARY KEY AUTOINCREMENT,
      name       TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );

    CREATE TABLE IF NOT EXISTS playlist_songs (
      id          INTEGER PRIMARY KEY AUTOINCREMENT,
      playlist_id INTEGER NOT NULL REFERENCES playlists(id) ON DELETE CASCADE,
      song_id     INTEGER NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
      position    INTEGER NOT NULL
    );

    CREATE INDEX IF NOT EXISTS idx_playlist_songs_playlist
      ON playlist_songs(playlist_id, position);

    -- Better Auth tables (schema generated by @better-auth/cli).
    CREATE TABLE IF NOT EXISTS "user" (
      "id" text not null primary key,
      "name" text not null,
      "email" text not null unique,
      "emailVerified" integer not null,
      "image" text,
      "createdAt" date not null,
      "updatedAt" date not null
    );
    CREATE TABLE IF NOT EXISTS "session" (
      "id" text not null primary key,
      "expiresAt" date not null,
      "token" text not null unique,
      "createdAt" date not null,
      "updatedAt" date not null,
      "ipAddress" text,
      "userAgent" text,
      "userId" text not null references "user" ("id") on delete cascade
    );
    CREATE TABLE IF NOT EXISTS "account" (
      "id" text not null primary key,
      "accountId" text not null,
      "providerId" text not null,
      "userId" text not null references "user" ("id") on delete cascade,
      "accessToken" text,
      "refreshToken" text,
      "idToken" text,
      "accessTokenExpiresAt" date,
      "refreshTokenExpiresAt" date,
      "scope" text,
      "password" text,
      "createdAt" date not null,
      "updatedAt" date not null
    );
    CREATE TABLE IF NOT EXISTS "verification" (
      "id" text not null primary key,
      "identifier" text not null,
      "value" text not null,
      "expiresAt" date not null,
      "createdAt" date not null,
      "updatedAt" date not null
    );
    CREATE INDEX IF NOT EXISTS "session_userId_idx" ON "session" ("userId");
    CREATE INDEX IF NOT EXISTS "account_userId_idx" ON "account" ("userId");
    CREATE INDEX IF NOT EXISTS "verification_identifier_idx" ON "verification" ("identifier");

    -- Friend invites (Cycle 21).
    CREATE TABLE IF NOT EXISTS invites (
      code       TEXT PRIMARY KEY,
      created_by TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      used_by    TEXT,
      used_at    TEXT
    );
    CREATE INDEX IF NOT EXISTS idx_invites_created_by ON invites(created_by);

    -- Playlist sharing (Cycle 22): read-only access granted to another user.
    CREATE TABLE IF NOT EXISTS playlist_shares (
      id          INTEGER PRIMARY KEY AUTOINCREMENT,
      playlist_id INTEGER NOT NULL REFERENCES playlists(id) ON DELETE CASCADE,
      shared_with TEXT NOT NULL,
      can_edit    INTEGER NOT NULL DEFAULT 0,
      created_at  TEXT NOT NULL DEFAULT (datetime('now')),
      UNIQUE(playlist_id, shared_with)
    );
    CREATE INDEX IF NOT EXISTS idx_playlist_shares_user
      ON playlist_shares(shared_with);

    -- Public share links (Cycle 23): one token per playlist, no auth to listen.
    CREATE TABLE IF NOT EXISTS public_shares (
      token       TEXT PRIMARY KEY,
      playlist_id INTEGER NOT NULL UNIQUE REFERENCES playlists(id) ON DELETE CASCADE,
      created_by  TEXT NOT NULL,
      created_at  TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `);

  // Metadata columns added post-MVP (Cycle 9). Added conditionally so existing
  // databases upgrade in place.
  const columns = (
    database.prepare("PRAGMA table_info(songs)").all() as { name: string }[]
  ).map((c) => c.name);
  if (!columns.includes("artist")) {
    database.exec("ALTER TABLE songs ADD COLUMN artist TEXT");
  }
  if (!columns.includes("album")) {
    database.exec("ALTER TABLE songs ADD COLUMN album TEXT");
  }
  if (!columns.includes("art_filename")) {
    database.exec("ALTER TABLE songs ADD COLUMN art_filename TEXT");
  }
  if (!columns.includes("duration")) {
    database.exec("ALTER TABLE songs ADD COLUMN duration REAL");
  }
  if (!columns.includes("play_count")) {
    database.exec(
      "ALTER TABLE songs ADD COLUMN play_count INTEGER NOT NULL DEFAULT 0"
    );
  }
  if (!columns.includes("last_played_at")) {
    database.exec("ALTER TABLE songs ADD COLUMN last_played_at TEXT");
  }
  if (!columns.includes("liked")) {
    database.exec("ALTER TABLE songs ADD COLUMN liked INTEGER NOT NULL DEFAULT 0");
  }
  // Multi-user ownership (Cycle 20). Nullable TEXT user id (no hard FK so
  // ordering/cascade stays simple); existing rows are claimed by the owner.
  if (!columns.includes("user_id")) {
    database.exec("ALTER TABLE songs ADD COLUMN user_id TEXT");
  }
  const plColumns = (
    database.prepare("PRAGMA table_info(playlists)").all() as { name: string }[]
  ).map((c) => c.name);
  if (!plColumns.includes("user_id")) {
    database.exec("ALTER TABLE playlists ADD COLUMN user_id TEXT");
  }
  // Collaborative sharing (Cycle 33): editors may add/remove tracks.
  const shareColumns = (
    database
      .prepare("PRAGMA table_info(playlist_shares)")
      .all() as { name: string }[]
  ).map((c) => c.name);
  if (shareColumns.length > 0 && !shareColumns.includes("can_edit")) {
    database.exec(
      "ALTER TABLE playlist_shares ADD COLUMN can_edit INTEGER NOT NULL DEFAULT 0"
    );
  }
}
