import Database from "better-sqlite3";
import { mkdirSync } from "node:fs";
import { dirname, join } from "node:path";

// Resolve data locations from the environment so the same code runs locally
// and inside Docker (where DATA_DIR=/data).
const DATA_DIR = process.env.DATA_DIR ?? join(process.cwd(), "..", "data");
export const MUSIC_DIR = join(DATA_DIR, "music");
export const ART_DIR = join(DATA_DIR, "art");
// Short looping "canvas" clips cut from a track's source video (link imports).
export const CLIPS_DIR = join(DATA_DIR, "clips");
const DB_PATH = join(DATA_DIR, "app.db");

let db: Database.Database | null = null;

// Returns a singleton database connection, creating the schema and required
// directories on first use.
export function getDb(): Database.Database {
  if (db) return db;

  mkdirSync(MUSIC_DIR, { recursive: true });
  mkdirSync(ART_DIR, { recursive: true });
  mkdirSync(CLIPS_DIR, { recursive: true });
  mkdirSync(dirname(DB_PATH), { recursive: true });

  db = new Database(DB_PATH);
  db.pragma("journal_mode = WAL");
  db.pragma("foreign_keys = ON");
  migrate(db);
  return db;
}

export function migrate(database: Database.Database): void {
  database.exec(`
    CREATE TABLE IF NOT EXISTS songs (
      id                INTEGER PRIMARY KEY AUTOINCREMENT,
      filename          TEXT NOT NULL,
      original_filename TEXT NOT NULL,
      uploaded_at       TEXT NOT NULL DEFAULT (datetime('now'))
    );

    CREATE TABLE IF NOT EXISTS playlists (
      id         INTEGER PRIMARY KEY AUTOINCREMENT,
      name       TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );

    CREATE TABLE IF NOT EXISTS playlist_songs (
      id          INTEGER PRIMARY KEY AUTOINCREMENT,
      playlist_id INTEGER NOT NULL REFERENCES playlists(id) ON DELETE CASCADE,
      song_id     INTEGER NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
      position    INTEGER NOT NULL
    );

    CREATE INDEX IF NOT EXISTS idx_playlist_songs_playlist
      ON playlist_songs(playlist_id, position);

    -- Better Auth tables (schema generated by @better-auth/cli).
    CREATE TABLE IF NOT EXISTS "user" (
      "id" text not null primary key,
      "name" text not null,
      "email" text not null unique,
      "emailVerified" integer not null,
      "image" text,
      "createdAt" date not null,
      "updatedAt" date not null
    );
    CREATE TABLE IF NOT EXISTS "session" (
      "id" text not null primary key,
      "expiresAt" date not null,
      "token" text not null unique,
      "createdAt" date not null,
      "updatedAt" date not null,
      "ipAddress" text,
      "userAgent" text,
      "userId" text not null references "user" ("id") on delete cascade
    );
    CREATE TABLE IF NOT EXISTS "account" (
      "id" text not null primary key,
      "accountId" text not null,
      "providerId" text not null,
      "userId" text not null references "user" ("id") on delete cascade,
      "accessToken" text,
      "refreshToken" text,
      "idToken" text,
      "accessTokenExpiresAt" date,
      "refreshTokenExpiresAt" date,
      "scope" text,
      "password" text,
      "createdAt" date not null,
      "updatedAt" date not null
    );
    CREATE TABLE IF NOT EXISTS "verification" (
      "id" text not null primary key,
      "identifier" text not null,
      "value" text not null,
      "expiresAt" date not null,
      "createdAt" date not null,
      "updatedAt" date not null
    );
    CREATE INDEX IF NOT EXISTS "session_userId_idx" ON "session" ("userId");
    CREATE INDEX IF NOT EXISTS "account_userId_idx" ON "account" ("userId");
    CREATE INDEX IF NOT EXISTS "verification_identifier_idx" ON "verification" ("identifier");

    -- Friend invites (Cycle 21).
    CREATE TABLE IF NOT EXISTS invites (
      code       TEXT PRIMARY KEY,
      created_by TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      used_by    TEXT,
      used_at    TEXT
    );
    CREATE INDEX IF NOT EXISTS idx_invites_created_by ON invites(created_by);

    -- Playlist sharing (Cycle 22): read-only access granted to another user.
    CREATE TABLE IF NOT EXISTS playlist_shares (
      id          INTEGER PRIMARY KEY AUTOINCREMENT,
      playlist_id INTEGER NOT NULL REFERENCES playlists(id) ON DELETE CASCADE,
      shared_with TEXT NOT NULL,
      can_edit    INTEGER NOT NULL DEFAULT 0,
      created_at  TEXT NOT NULL DEFAULT (datetime('now')),
      UNIQUE(playlist_id, shared_with)
    );
    CREATE INDEX IF NOT EXISTS idx_playlist_shares_user
      ON playlist_shares(shared_with);

    -- Public share links (Cycle 23): one token per playlist, no auth to listen.
    CREATE TABLE IF NOT EXISTS public_shares (
      token       TEXT PRIMARY KEY,
      playlist_id INTEGER NOT NULL UNIQUE REFERENCES playlists(id) ON DELETE CASCADE,
      created_by  TEXT NOT NULL,
      created_at  TEXT NOT NULL DEFAULT (datetime('now'))
    );

    -- Public share links for a single song (Cycle 39).
    CREATE TABLE IF NOT EXISTS song_public_shares (
      token      TEXT PRIMARY KEY,
      song_id    INTEGER NOT NULL UNIQUE REFERENCES songs(id) ON DELETE CASCADE,
      created_by TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
    CREATE TABLE IF NOT EXISTS artist_public_shares (
      token      TEXT PRIMARY KEY,
      user_id    TEXT NOT NULL,
      artist     TEXT NOT NULL,
      created_by TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      UNIQUE(user_id, artist)
    );

    -- Mutual friendships: one row per ordered pair. 'pending' until the
    -- addressee accepts, then 'accepted' (the relationship is undirected once
    -- accepted, so reads check both the requester and addressee sides).
    CREATE TABLE IF NOT EXISTS friendships (
      id           INTEGER PRIMARY KEY AUTOINCREMENT,
      requester_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
      addressee_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
      status       TEXT NOT NULL DEFAULT 'pending', -- 'pending' | 'accepted'
      created_at   TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at   TEXT NOT NULL DEFAULT (datetime('now')),
      UNIQUE(requester_id, addressee_id)
    );
    CREATE INDEX IF NOT EXISTS idx_friendships_requester
      ON friendships(requester_id, status);
    CREATE INDEX IF NOT EXISTS idx_friendships_addressee
      ON friendships(addressee_id, status);

    -- Cross-device sync: remembers which device was last the audio output for a
    -- user, so a refresh (or server restart) defaults back to it instead of
    -- jumping to another open device. Moving output is a manual "listen here".
    CREATE TABLE IF NOT EXISTS sync_active_device (
      user_id          TEXT PRIMARY KEY,
      active_device_id TEXT,
      updated_at       TEXT NOT NULL DEFAULT (datetime('now'))
    );

    -- Custom artist avatar images (per user). When absent, the UI falls back to
    -- the artist's top track embedded art. The file lives in the art directory.
    CREATE TABLE IF NOT EXISTS artist_images (
      user_id    TEXT NOT NULL,
      artist     TEXT NOT NULL,
      filename   TEXT NOT NULL,
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      PRIMARY KEY (user_id, artist)
    );

    -- Last now-playing snapshot per user (queue, current track, position, etc.),
    -- so playback can resume where it left off on ANY device. Stored as a JSON
    -- blob; updated_at (epoch ms) lets the client pick the freshest of this and
    -- its local copy.
    CREATE TABLE IF NOT EXISTS playback_state (
      user_id    TEXT PRIMARY KEY,
      snapshot   TEXT NOT NULL,
      updated_at INTEGER NOT NULL
    );

    -- A dedicated, revocable password per user for Subsonic/OpenSubsonic API
    -- clients (DSub, Symfonium, ...). The login password is irreversibly hashed
    -- by Better Auth, but Subsonic token auth needs the plaintext to verify, so
    -- this is a separate generated credential the user can regenerate any time.
    CREATE TABLE IF NOT EXISTS subsonic_credentials (
      user_id    TEXT PRIMARY KEY,
      password   TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );

    -- Per-user ListenBrainz scrobbling. The user pastes their personal
    -- ListenBrainz token; we submit a "listen" each time they finish a track.
    -- username is cached from token validation for display in settings.
    CREATE TABLE IF NOT EXISTS listenbrainz_tokens (
      user_id    TEXT PRIMARY KEY,
      token      TEXT NOT NULL,
      username   TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );

    -- Per-user Last.fm scrobbling. Stores only the permanent session key from
    -- the web-auth exchange (never the password); username cached for display.
    CREATE TABLE IF NOT EXISTS lastfm_sessions (
      user_id     TEXT PRIMARY KEY,
      session_key TEXT NOT NULL,
      username    TEXT,
      created_at  TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `);

  // Metadata columns added post-MVP (Cycle 9). Added conditionally so existing
  // databases upgrade in place.
  const columns = (
    database.prepare("PRAGMA table_info(songs)").all() as { name: string }[]
  ).map((c) => c.name);
  if (!columns.includes("artist")) {
    database.exec("ALTER TABLE songs ADD COLUMN artist TEXT");
  }
  if (!columns.includes("album")) {
    database.exec("ALTER TABLE songs ADD COLUMN album TEXT");
  }
  if (!columns.includes("art_filename")) {
    database.exec("ALTER TABLE songs ADD COLUMN art_filename TEXT");
  }
  if (!columns.includes("duration")) {
    database.exec("ALTER TABLE songs ADD COLUMN duration REAL");
  }
  if (!columns.includes("play_count")) {
    database.exec(
      "ALTER TABLE songs ADD COLUMN play_count INTEGER NOT NULL DEFAULT 0"
    );
  }
  if (!columns.includes("last_played_at")) {
    database.exec("ALTER TABLE songs ADD COLUMN last_played_at TEXT");
  }
  if (!columns.includes("liked")) {
    database.exec("ALTER TABLE songs ADD COLUMN liked INTEGER NOT NULL DEFAULT 0");
  }
  // Multi-user ownership (Cycle 20). Nullable TEXT user id (no hard FK so
  // ordering/cascade stays simple); existing rows are claimed by the owner.
  if (!columns.includes("user_id")) {
    database.exec("ALTER TABLE songs ADD COLUMN user_id TEXT");
  }
  // Integrated loudness in LUFS (EBU R128), measured by ffmpeg, for volume
  // normalization. Null until analyzed.
  if (!columns.includes("loudness")) {
    database.exec("ALTER TABLE songs ADD COLUMN loudness REAL");
  }
  // Manual sort order within a derived grouping (e.g. an artist's tracks).
  // Null until the user drags to reorder.
  if (!columns.includes("sort_order")) {
    database.exec("ALTER TABLE songs ADD COLUMN sort_order REAL");
  }
  // Uploaded/imported tracks awaiting review; hidden from the library until the
  // user confirms them. Existing rows default to 0 (already in the library).
  if (!columns.includes("pending")) {
    database.exec(
      "ALTER TABLE songs ADD COLUMN pending INTEGER NOT NULL DEFAULT 0"
    );
  }
  // Source link for tracks imported via yt-dlp; lets us re-fetch video frames
  // to offer as alternative cover art. Null for file uploads.
  if (!columns.includes("source_url")) {
    database.exec("ALTER TABLE songs ADD COLUMN source_url TEXT");
  }
  // Filename of a cached looping "canvas" clip cut from the source video, shown
  // in the expanded player. Null until generated (lazily on first expand).
  if (!columns.includes("clip_filename")) {
    database.exec("ALTER TABLE songs ADD COLUMN clip_filename TEXT");
  }
  // MusicBrainz recording MBID captured at import; lets ListenBrainz match
  // scrobbles precisely. Null for file uploads / no-match imports (those
  // scrobble by artist+track name instead).
  if (!columns.includes("mb_recording_id")) {
    database.exec("ALTER TABLE songs ADD COLUMN mb_recording_id TEXT");
  }
  // Per-song opt-out: when 1, the expanded player won't show this song's clip.
  if (!columns.includes("clip_disabled")) {
    database.exec(
      "ALTER TABLE songs ADD COLUMN clip_disabled INTEGER NOT NULL DEFAULT 0"
    );
  }
  const plColumns = (
    database.prepare("PRAGMA table_info(playlists)").all() as { name: string }[]
  ).map((c) => c.name);
  if (!plColumns.includes("user_id")) {
    database.exec("ALTER TABLE playlists ADD COLUMN user_id TEXT");
  }
  // Optional custom cover image (in ART_DIR). Null → fall back to the first
  // track's album art.
  if (!plColumns.includes("image_filename")) {
    database.exec("ALTER TABLE playlists ADD COLUMN image_filename TEXT");
  }
  // Links a saved copy back to the shared playlist it was copied from, so the
  // "Add to my playlists" action can toggle (and we can tell it's already saved).
  if (!plColumns.includes("copied_from")) {
    database.exec("ALTER TABLE playlists ADD COLUMN copied_from INTEGER");
  }
  // Org/team playlists (auto-created per email domain): when set, the playlist
  // is the shared Team playlist for that domain and has no personal user_id, so
  // it never shows in anyone's "your playlists". One per domain (unique index).
  if (!plColumns.includes("org_domain")) {
    database.exec("ALTER TABLE playlists ADD COLUMN org_domain TEXT");
  }
  database.exec(
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_playlists_org_domain
       ON playlists(org_domain) WHERE org_domain IS NOT NULL`
  );
  // Whether we've attempted to fetch the company logo for an org playlist's
  // cover (so we try exactly once, not on every load).
  if (!plColumns.includes("org_logo_tried")) {
    database.exec(
      "ALTER TABLE playlists ADD COLUMN org_logo_tried INTEGER NOT NULL DEFAULT 0"
    );
  }
  // Global playlists: shared with every user on the system (collaborative,
  // per-song ownership). The owner still owns/manages the playlist itself.
  if (!plColumns.includes("is_global")) {
    database.exec(
      "ALTER TABLE playlists ADD COLUMN is_global INTEGER NOT NULL DEFAULT 0"
    );
  }
  // Collaborative sharing (Cycle 33): editors may add/remove tracks.
  const shareColumns = (
    database
      .prepare("PRAGMA table_info(playlist_shares)")
      .all() as { name: string }[]
  ).map((c) => c.name);
  if (shareColumns.length > 0 && !shareColumns.includes("can_edit")) {
    database.exec(
      "ALTER TABLE playlist_shares ADD COLUMN can_edit INTEGER NOT NULL DEFAULT 0"
    );
  }
  // Who added each track to a playlist (for collaborative playlists). Existing
  // rows are backfilled to the playlist's owner.
  const psColumns = (
    database
      .prepare("PRAGMA table_info(playlist_songs)")
      .all() as { name: string }[]
  ).map((c) => c.name);
  if (psColumns.length > 0 && !psColumns.includes("added_by")) {
    database.exec("ALTER TABLE playlist_songs ADD COLUMN added_by TEXT");
    database.exec(
      `UPDATE playlist_songs SET added_by = (
         SELECT p.user_id FROM playlists p WHERE p.id = playlist_songs.playlist_id
       ) WHERE added_by IS NULL`
    );
  }
}
